### ISSUE TITLE
Requests for earlier version of a layer still return the newest version of the layer

### ISSUE THREAD

**Issue by ella-wynn** [jcla490/landfire-python#122]
I'm looking to compare a 2022 layer to the 2019 layer. My requests for the 220CH_22 layer work fine:

```python
lf.request_data(layers=["220CH_22"], output_path=zip_path, backoff_base_value=10)
``` 

but when I change the layers argument to "220CH_19", the API calls spits out the following message, "Most recent message is `US_220CH_22`". I see that the url includes "&Layer_List=220CH_22", confirming that my input is ignored.

Is there a way to override the request for the most recent layer?

**Comment by jcla490** [comment]
Hi @ella-wynn, thanks for this issue, I'll try to get to this tomorrow or at latest over the weekend!

**Comment by ella-wynn** [comment]
This is my bad, actually. I misread the canopy height variables, so my request was incorrect. It should have been "200_CH19", not "220CH_19".

![image](https://github.com/user-attachments/assets/df4c3e04-b774-4d57-8167-74a9531bca73)

**Comment by ella-wynn** [comment]
This is my bad, actually. I misread the canopy height variables, so my request was incorrect. It should have been "200_CH19", not "220CH_19".

![image](https://github.com/user-attachments/assets/df4c3e04-b774-4d57-8167-74a9531bca73)
