### ISSUE TITLE
Question: gdal conversion to old LCP format (farsite4)

### ISSUE THREAD

**Issue by dschwilk** [jcla490/landfire-python#66]
Thank you for this API! It has worked great to grab data layers for some modelling simulation efforts a student of mine is attempting.  I have a question you might be able to answer, but it is not a bug or feature request for your code. I apologize.

We are using a command-line version of FARSITE (eg forked from the 2016 "linux" code release). The goal is batch runs for creation of summary statistics over parameter sets. The issue is that this version of the fire growth model is hard-coded to only use old style LCP files not GeoTIFF. I had thought conversion would be trivial with gdal, but I was mistaken.

With command line `gdal_translate -ot INT16 -of LCP test.tif test.lcp` I get memory-related crashes of the gdal libraries under multiple installations of the gdal libraries (eg ubuntu-gis-stable or unstable or distro version). I've not filed any gdal bug report because I'm not sure that I'm not doing something stupid.

result gdal_translate call:
```
Input file size is 102, 102
double free or corruption (out)
Aborted (core dumped)
```
The problem is the similar using gdal through R terra package or python gdal interface (either crashes or errors that may indicate exception handling in the API). I've tried passing all the gdal options listed at https://gdal.org/drivers/raster/lcp.html to  terra::writeRaster in R. Perhaps you know offhand how this is best done?

**Comment by jcla490** [comment]
Hi Dr. Schwilk,
Very quick thoughts, are you able to use the new CLI for FARSITE in https://www.alturassolutions.com/FB/FB_API.htm. 

I'll circle back later after I think on this a bit more!

**Comment by dschwilk** [comment]
Thanks for the response! I should grab a windows machine from a colleague and test that. If that works, I guess a workaround is setting up a windows box for this and then getting the rest of the R and python workflow to work on windows  ---  as much as that pains me :).  Or I can try with wine.

However, it looks from the readme and example that it requires lcp files. The executable name also suggests the TestFarsite cli is probably the same as that built by the code base that Stuart Brittain posted in 2016 (http://sbrittain.net/Farsite/Distrib/Linux/Farsite_Linux.htm )  which is the original source for the version I'm working with at https://github.com/dschwilk/farsite --- except the current code has the ability to handle gridded winds that the Missoula fire lab folks added around 2019 (they had a github repo up until March this year and I had grabbed it at one point so was able to merged in their gridded winds changes with my more minor code updating).

 The other solution I guess is to add gdal support and geotiff input to the C++ cli version . . . . But that would take some real work. It would be great for the community overall to have a command line and open source version for running simulations.

**Comment by dschwilk** [comment]
I went ahead and opened an issue OSGeo/gdal: https://github.com/OSGeo/gdal/issues/7561

**Comment by dschwilk** [comment]
I'll close this. Thanks for the response. It appears to be a bug in the gdal LCP driver.  Best wishes.

**Comment by dschwilk** [comment]
Note for anyone who finds this. Until the fix of https://github.com/OSGeo/gdal/issues/7561 winds its way to a a release of gdal, the workaround is to convert any aspect values of -1 (what landfire uses for aspect at zero slope) to zeroes. After that, the LCP driver will not crash. I've done this with python3 rasterio.
